# schema: "https://echokarriere-dev.azurewebsites.net/graphql"
schema: "http://localhost:8080/graphql"
documents:
  - "src/**/*.{gql,graphql}"
  - "src/**/*.{ts,tsx}"
extensions:
  codegen:
    generates:
      ./schema.graphql:
        plugins:
          - schema-ast
      ./introspection.json:
        plugins:
          - introspection
      ./src/graphql/index.ts:
        config:
          withHooks: true
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
    hooks:
      afterAllFileWrite:
        - prettier --write
    overwrite: true
